# Camera and local display
iq_dir=/etc/iqfiles
frame_source=vpss
lvgl=true

# Leave empty to disable RTMP publishing.
rtmp_url=rtmp://192.168.0.104/live/stream

# H.265 video RTSP service
rtsp_enabled=true
rtsp_port=554
rtsp_path=/live/0
